etcd:
  image: schuylr/etcd:latest
  labels:
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  environment:
    RANCHER_DEBUG: '${DEBUG}'
  volumes:
  - /var/etcd:/pdata
